### ISSUE TITLE
Question regarding method getAddress(uint8_t* deviceAddress, uint8_t index)

### ISSUE THREAD

**Issue by hasenradball** [milesburton/Arduino-Temperature-Control-Library#166]
Hi,

I actually do not catched the benefit of using this method.
As I read the code this method searches for the `deviceAddress` at this `index`, right?
But was is the benefit of it?
If I know the the `deviceAddress` I am able to search via `deviceAddress` and if I know the `index` I can use the `index`.
Is the index Array always automatically?

**Comment by MalcolmBoura** [comment]
There is an additional problem. This function does not belong in DallasTemperature since it acts on the whole bus and it can return devices that DallasTemperature does not support. It should be part of OneWire or a OneWire extension class that inherits from OneWire. I am currently writing an extension class to tackle this and a number of other similar issues.

The advantage of using index is that it is only one byte as opposed to 8 for the full address but it is inefficient since it has to search the bus to find things.

**Comment by MalcolmBoura** [comment]
This issue has considerable overlap with #166. Oops, I missed that when looking through before creating this.

**Comment by MalcolmBoura** [comment]
I am thinking about automating the identification of devices and storing the address in EEPROM. Do all Arduinos have persistent writable storage?
What I have in mind is something like:
1. Send command to Arduino, probably over serial but could be a press button, to start identification process
2. Iterate the bus to find DS18 family devices, checking that all are at a lowish temperature, say <50C.
2. Report the number of devices.
3. Ask for first device to be indicated. Human dips the device in hot water. Arduino stores first device address in EEPROM.
4. Repeat step 3 for subsequent devices.

#define DALLAS_TEMPERATURE_IDENTIFICATION_THRESHOLD 50
#define DALLAS_TEMPERATURE_IDENTIFICATION_STORAGE 0 /* address in EEPROM */

That way the user has a safe way to identify which device is which without having to muck about with addresses. An alternative to EEPROM would be to generate code for cut and paste but that is messy.

**Comment by RobTillaart** [comment]
Not all processors have EEPROM afaik,. Furthermore it will be hard to know which EEPROM addresses to use as the EEPROM could also be used for other storage needs of the user. Question is how to prevent conflicts?

The proces of identification could be easier by adding just a sensor at a time. The new ID in the list is the one added. 
No need to play with water (unfortunately :)

**Comment by MalcolmBoura** [comment]
That is why I suggested #defining the base address in the EEPROM. The Arduino IDE is not good at handling configuration but I use a Makefile and I have a line `CXXFLAGS += -include config.h` which ensures that all files see the same configuration values.

I have a strings of sensors along wires and they are very firmly in place in order to provide environmental protection. Solder + hot melt + shrink wrap. I could document the addresses at or prior to assembly but that is a faf. An alternative to hot water would be a lower threshold, say 30C, and hold in the fingers for a few seconds.

**Comment by MalcolmBoura** [comment]
I am fairly sure that you can use the alarms to store ids and still use the alarms but you can not make them persistent.

Anyway, I have given this quite a bit of consideration over the past few days and come to the conclusion that a OneWireManager is needed that will look after the mapping between deviceIndex, OneWire instance, and deviceAddress. See #195 for more detail.
